"""add zak_token to zoom_meetings1

Revision ID: f2e6c234a755
Revises: 
Create Date: 2025-03-13 03:10:36.490170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e6c234a755'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zoom_meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zak_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zoom_meetings', schema=None) as batch_op:
        batch_op.drop_column('zak_token')

    # ### end Alembic commands ###
