"""Add card_assignees table for multiple assignees

Revision ID: fb038758541f
Revises: e848b5074310
Create Date: 2025-04-25 00:31:26.000495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb038758541f'
down_revision = 'e848b5074310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_list')
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('color_id')

    with op.batch_alter_table('lobbies', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_lobbies_archived_by_users',  # добавили имя
            'users',
            ['archived_by'],
            ['id'],
            ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobbies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lobbies_archived_by_users', type_='foreignkey')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_id', sa.TEXT(), server_default=sa.text("'default'"), nullable=True))

    op.create_table('_alembic_tmp_list',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=100), nullable=False),
        sa.Column('board_id', sa.INTEGER(), nullable=False),
        sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
        sa.Column('color', sa.VARCHAR(length=50), nullable=True),
        sa.Column('text_color', sa.VARCHAR(length=50), nullable=True),
        sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
